export {
  DocumentSchema,
  DocumentTypeSchema,
  TranscriptionFormatSchema,
  DocumentSectionSchema,
  DocumentSectionTypeSchema,
  DocumentListResponseSchema,
  DocumentListQuerySchema,
  DocumentPatchSchema,
  FieldProvenanceSchema,
  SearchQuerySchema,
  SearchResultSchema,
  SearchResponseSchema,
  ErrorResponseSchema,
} from './schemas/document.js';

export type {
  Document,
  DocumentType,
  TranscriptionFormat,
  DocumentSection,
  DocumentSectionType,
  DocumentListResponse,
  DocumentListQuery,
  DocumentPatch,
  FieldProvenance,
  SearchQuery,
  SearchResult,
  SearchResponse,
  ErrorResponse,
} from './schemas/document.js';
